"""
Created on April 10, 2017
@author: aramael
"""

#              R    G    B
BLACK      = (  0,   0,   0)
WHITE      = (255, 255, 255)
LIGHT_GRAY = (205, 205, 205)
GRAY       = ( 79,  79,  79)

# Gradient Buttons
#                          R    G    B
PHOSPHORIC_LIGHT_COLOR = (187, 252,   0)
PHOSPHORIC_DARK_COLOR  = (159, 255,   0)
PHOSPHORIC_TEXT_COLOR  = BLACK
PHOSPHORIC_COLORS      = [PHOSPHORIC_LIGHT_COLOR, PHOSPHORIC_DARK_COLOR]

CYAN_LIGHT_COLOR       = (104, 251, 238)
CYAN_DARK_COLOR        = ( 34, 201, 217)
CYAN_TEXT_COLOR        = WHITE
CYAN_COLORS            = [CYAN_LIGHT_COLOR, CYAN_DARK_COLOR]


PINK_LIGHT_COLOR       = (255,  20,  17)
PINK_DARK_COLOR        = (253,   8, 171)
PINK_TEXT_COLOR        = WHITE
PINK_COLORS            = [PINK_LIGHT_COLOR, PINK_DARK_COLOR]


# Classic Buttons
#                       R    G    B
BUTTON_1_BG_COLOR   = (  3,  52,  30)
BUTTON_1_TEXT_COLOR = (  3, 155, 254)

BUTTON_2_BG_COLOR   = GRAY
BUTTON_2_TEXT_COLOR = LIGHT_GRAY

BUTTON_3_BG_COLOR   = GRAY
BUTTON_3_TEXT_COLOR = ( 97, 211,  255)

SCREEN_BG_COLOR = BLACK
BUTTON_BG_COLOR = GRAY