"""
Created on April 17, 2017
@author: aramael
"""
from enum import Enum

class Page(Enum):
	UI_WIN_SPLASH_SCREEN = 1
	UI_WIN_PASSCODE_LOCK_SCREEN = 2
	UI_WIN_HOME_SCREEN = 3
	UI_WIN_MAIN_MENU_SCREEN = 4
	UI_WIN_MANUAL_JOG_CARTESIAN_SCREEN = 5
	UI_WIN_MANUAL_JOG_JOINT_SCREEN = 6
	UI_WIN_PROGRAM_SELECTION_SCREEN = 7
	UI_WIN_PHOTO_CAPTURE_SCREEN = 8
	UI_WIN_CURVES_SELECTION_SCREEN = 9
	UI_WIN_MESSAGES_LIST_SCREEN = 10
	UI_WIN_MESSAGE_SCREEN = 11